import logging
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
import uvicorn

from brain import GeminiBrain

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)

app = FastAPI(
    title="Malaz API",
    description="API for Malaz Parenting Assistant. This provides an AI-driven chat interface for parenting advice.",
    version="1.0.0",
    docs_url="/docs",
    redoc_url="/redoc"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Allows all origins, adjust in production
    allow_credentials=True,
    allow_methods=["*"],  # Allows all methods
    allow_headers=["*"],  # Allows all headers
)

bot = GeminiBrain()

class ChatRequest(BaseModel):
    user_id: str = Field(default="guest", description="Unique identifier for the user/child")
    message: str = Field(..., description="The message from the user")

class ChatResponse(BaseModel):
    reply: str = Field(..., description="The response from the Gemini model")

class HealthResponse(BaseModel):
    status: str

@app.get("/", response_model=HealthResponse, summary="Check API Health", response_description="Returns the current health status of the API", tags=["Health"])
def health():
    return {"status": "healthy"}

@app.post("/chat", response_model=ChatResponse, summary="Chat with Malaz Assistant", response_description="The response generated by the Malaz AI assistant", tags=["Chat"])
def chat(request_data: ChatRequest):
    if not request_data.message.strip():
        logger.warning(f"Empty message received from user: {request_data.user_id}")
        raise HTTPException(status_code=400, detail="No message provided")

    try:
        logger.info(f"Processing chat request for user: {request_data.user_id}")

        reply = bot.ask_gemini(request_data.user_id, request_data.message)
        logger.info(f"Successfully generated reply for user: {request_data.user_id}")
        return {"reply": reply}
    except Exception as e:
        logger.error(f"Error processing chat request for user {request_data.user_id}: {str(e)}", exc_info=True)
        raise HTTPException(status_code=500, detail="An internal error occurred while processing your request.")

if __name__ == '__main__':
    logger.info("Starting Malaz API on Port 5000...")
    uvicorn.run(app, host='0.0.0.0', port=5000)